# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: JAX PR

on: 
  push:
    branches:
      - jax
  pull_request:
    branches:
      - jax 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip &&
        git clone https://github.com/d2l-ai/d2l-en.git &&
        cd d2l-en && python setup.py develop &&
        pip install jax jaxlib jupyterlab &&
        pip install git+https://github.com/d2l-ai/d2l-book &&
        pip install docutils==0.15.2
    - name: Check outputs
      run: |
        cd d2l-en &&
        d2lbook build outputcheck
    - name: Eval
      run: |
        cd d2l-en &&
        d2lbook build eval --tab jax
    - name: build library
      run: |
        cd d2l-en &&
        d2lbook build lib
  
